name: deploy
on:
  push:
    branches-ignore:
      - main
    paths:
      - "apps/throwtrash-alexa-skill/**"
      - "packages/trash-common/**"
      - ".github/**"
  pull_request:
    branches:
      - deploy
    types: [opened, synchronize]
    paths:
      - "apps/throwtrash-alexa-skill/**"
      - "packages/trash-common/**"
      - ".github/**"
permissions:
  id-token: write
  contents: read
  issues: write
  pull-requests: write
jobs:
  set-stage:
    runs-on: ubuntu-latest
    outputs:
      STAGE: ${{ steps.set-stage.outputs.STAGE }}
    steps:
      - name: Set stage
        id: set-stage
        run: |
          if [ ${{ github.event_name }} == "pull_request" -o ${{ github.ref }} == "refs/heads/deploy" ]; then
            echo "STAGE=prod" >> $GITHUB_OUTPUT
          else
            echo "STAGE=dev" >> $GITHUB_OUTPUT
          fi
  build-and-deploy:
    environment: ${{ needs.set-stage.outputs.STAGE }}
    needs:
      - set-stage
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        id: configure-aws-credentials
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/throwtrash-skill-deploy-role
          role-session-name: GitHubActions
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.0
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: test
        if: github.event_name == 'push'
        run: |
          sudo npm install -g ask-cli@2.1.1 --unsafe-perm
          mkdir -p ~/.ask
          echo "${{ secrets.ASK_CLI_CONFIG }}" > ~/.ask/cli_config
          export APP_ID=$APPID
          pnpm --filter throwtrash-alexa-skill run test
      - name: build
        run: |
          pnpm --filter throwtrash-alexa-skill run build
          pnpm --config.node-linker=hoisted --filter throwtrash-alexa-skill deploy --prod apps/throwtrash-alexa-skill/app/deploy
      - name: layer-install
        run: |
          layer_root="apps/throwtrash-alexa-skill/app/layer/nodejs"
          rm -rf "${layer_root}"
          mkdir -p "${layer_root}"
          mv "apps/throwtrash-alexa-skill/app/deploy/node_modules" "${layer_root}/node_modules"
      - uses: hashicorp/setup-terraform@v3
      - name: terraform-init
        working-directory: apps/throwtrash-alexa-skill
        run: |
          # Terraformの初期化
          terraform init -backend-config="region=${{ vars.AWS_DEFAULT_REGION }}" -backend-config="bucket=throwtrash-tfstate-${{ needs.set-stage.outputs.STAGE }}"
          # TFVARファイルを作成
          echo "AppID=\"${{ vars.ALEXA_APP_ID }}\"" >> terraform.tfvars
          echo "ApiUrl=\"${{ vars.MECAB_API_URL }}\"" >> terraform.tfvars
          echo "ApiKey=\"${{ secrets.MECAB_API_KEY }}\"" >> terraform.tfvars
          echo "ReminderProductID=\"${{ vars.REMINDER_PRODUCT_ID }}\"" >> terraform.tfvars
          echo "RunLevel=\"${{ vars.RUNLEVEL }}\"" >> terraform.tfvars
          echo "stage=\"${{ needs.set-stage.outputs.STAGE }}\"" >> terraform.tfvars
      - name: terraform-plan
        id: terraform-plan
        working-directory: apps/throwtrash-alexa-skill
        run: |
          terraform plan -var-file=terraform.tfvars -no-color
      - name: terraform-apply
        if: github.event_name == 'push'
        working-directory: apps/throwtrash-alexa-skill
        run: |
          terraform apply -auto-approve -var-file=terraform.tfvars
