name: prod-deploy
on:
  push:
    branches:
    - release
    paths:
      - "apps/frontend/**"
      - "apps/backend/**"
      - "apps/mobile/**"
      - "cloudfront/**"
      - "packages/trash-common/**"
      - ".github/**"
      - "!.github/workflows/alarm-deploy.yml"
      - "!.github/workflows/alarm-plan.yml"
permissions:
  contents: read
  id-token: write
  pull-requests: read

jobs:
  get-pr-number:
    runs-on: ubuntu-latest
    outputs:
      pr_number: ${{ steps.findPr.outputs.pr }}
    steps:
      - uses: jwalton/gh-find-current-pr@master
        id: findPr
        with:
          state: closed
      - name: Set PR number
        run: echo "pr_number=${{ steps.findPr.outputs.pr }}" >> $GITHUB_OUTPUT
  frontend-deploy:
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: AWS Set up
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/throwtrash-frontend-deploy-role
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
      - uses: ./.github/actions/frontend/build
        with:
          frontend-stage: ${{ vars.FRONTEND_STAGE }}
          api-base: ${{ vars.CF_DOMAIN_NAME }}/backend/${{ vars.BACKEND_STAGE }}
      - uses: ./.github/actions/frontend/deploy
        with:
          frontend-stage: ${{ vars.FRONTEND_STAGE }}
          bucket: throwtrash
  backend-deploy:
    needs: ["get-pr-number"]
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/throwtrash-api-deploy-role
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
      - name: Backend DB ChangeSet Execute
        run: |
          CHANGE_SET_NAME="deploy-${{ needs.get-pr-number.outputs.pr_number }}"
          STACK_NAME="throwtrash-backend-db"
          REGION="${{ vars.AWS_DEFAULT_REGION }}"
          STATUS=$(aws cloudformation describe-change-set --change-set-name "${CHANGE_SET_NAME}" --stack-name "${STACK_NAME}" --query 'Status' --output text --region "${REGION}")
          if [ "${STATUS}" = "CREATE_COMPLETE" ]; then
            aws cloudformation execute-change-set --change-set-name "${CHANGE_SET_NAME}" --stack-name "${STACK_NAME}" --region "${REGION}"
          else
            REASON=$(aws cloudformation describe-change-set --change-set-name "${CHANGE_SET_NAME}" --stack-name "${STACK_NAME}" --query 'StatusReason' --output text --region "${REGION}")
            echo "Skip execute change-set: stack=${STACK_NAME}, changeSet=${CHANGE_SET_NAME}, status=${STATUS}, reason=${REASON}"
          fi
      - name: Backend ChangeSet Execute
        run: |
          CHANGE_SET_NAME="deploy-${{ needs.get-pr-number.outputs.pr_number }}"
          STACK_NAME="throwtrash-backend-${{ vars.BACKEND_STAGE }}"
          REGION="${{ vars.AWS_DEFAULT_REGION }}"
          STATUS=$(aws cloudformation describe-change-set --change-set-name "${CHANGE_SET_NAME}" --stack-name "${STACK_NAME}" --query 'Status' --output text --region "${REGION}")
          if [ "${STATUS}" = "CREATE_COMPLETE" ]; then
            aws cloudformation execute-change-set --change-set-name "${CHANGE_SET_NAME}" --stack-name "${STACK_NAME}" --region "${REGION}"
          else
            REASON=$(aws cloudformation describe-change-set --change-set-name "${CHANGE_SET_NAME}" --stack-name "${STACK_NAME}" --query 'StatusReason' --output text --region "${REGION}")
            echo "Skip execute change-set: stack=${STACK_NAME}, changeSet=${CHANGE_SET_NAME}, status=${STATUS}, reason=${REASON}"
          fi
  mobile-backend-deploy:
    needs: ["get-pr-number"]
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/throwtrash-api-deploy-role
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
      - name: Mobile Backend DB ChangeSet Execute
        run: |
          CHANGE_SET_NAME="deploy-${{ needs.get-pr-number.outputs.pr_number }}"
          STACK_NAME="throwtrash-mobile-db"
          REGION="${{ vars.AWS_DEFAULT_REGION }}"
          STATUS=$(aws cloudformation describe-change-set --change-set-name "${CHANGE_SET_NAME}" --stack-name "${STACK_NAME}" --query 'Status' --output text --region "${REGION}")
          if [ "${STATUS}" = "CREATE_COMPLETE" ]; then
            aws cloudformation execute-change-set --change-set-name "${CHANGE_SET_NAME}" --stack-name "${STACK_NAME}" --region "${REGION}"
          else
            REASON=$(aws cloudformation describe-change-set --change-set-name "${CHANGE_SET_NAME}" --stack-name "${STACK_NAME}" --query 'StatusReason' --output text --region "${REGION}")
            echo "Skip execute change-set: stack=${STACK_NAME}, changeSet=${CHANGE_SET_NAME}, status=${STATUS}, reason=${REASON}"
          fi
      - name: Mobile Backend ChangeSet Execute
        run: |
          CHANGE_SET_NAME="deploy-${{ needs.get-pr-number.outputs.pr_number }}"
          STACK_NAME="throwtrash-mobile-${{ vars.MOBILE_API_STAGE }}"
          REGION="${{ vars.AWS_DEFAULT_REGION }}"
          STATUS=$(aws cloudformation describe-change-set --change-set-name "${CHANGE_SET_NAME}" --stack-name "${STACK_NAME}" --query 'Status' --output text --region "${REGION}")
          if [ "${STATUS}" = "CREATE_COMPLETE" ]; then
            aws cloudformation execute-change-set --change-set-name "${CHANGE_SET_NAME}" --stack-name "${STACK_NAME}" --region "${REGION}"
          else
            REASON=$(aws cloudformation describe-change-set --change-set-name "${CHANGE_SET_NAME}" --stack-name "${STACK_NAME}" --query 'StatusReason' --output text --region "${REGION}")
            echo "Skip execute change-set: stack=${STACK_NAME}, changeSet=${CHANGE_SET_NAME}, status=${STATUS}, reason=${REASON}"
          fi

  cloudfront-deploy:
    needs: ["frontend-deploy", "backend-deploy", "mobile-backend-deploy"]
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: AWS Set up
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ vars.AWS_ACCOUNT_ID }}:role/throwtrash-frontend-deploy-role
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.12.0
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'
      - name: Install CDK dependencies
        run: pnpm --filter cloudfront install --frozen-lockfile
      - name: Deploy CloudFront
        env:
          CF_STAGE: prod
          CF_DOMAIN_NAME: ${{ vars.CF_DOMAIN_NAME }}
          CF_CERT_ARN: ${{ vars.CF_CERT_ARN }}
          CF_BACKEND_API_DOMAIN: ${{ vars.CF_BACKEND_API_DOMAIN}}
          CF_MOBILE_API_DOMAIN: ${{ vars.CF_MOBILE_API_DOMAIN}}
          CF_ALARM_API_DOMAIN: ${{ vars.CF_ALARM_API_DOMAIN }}
          CF_FRONTEND_BUCKET: throwtrash
        run: |
          pnpm --filter cloudfront run deploy:prod
      - name: Invalidate CloudFront cache
        env:
          STACK_NAME: throwtrash-cloudfront-prod
        run: |
          DISTRIBUTION_ID=$(aws cloudformation describe-stacks --stack-name "${STACK_NAME}" --query "Stacks[0].Outputs[?OutputKey=='DistributionId'].OutputValue" --output text --region us-east-1)
          aws cloudfront create-invalidation --distribution-id "${DISTRIBUTION_ID}" --paths "/*" --region us-east-1
